### ISSUE TITLE
More data

### ISSUE THREAD

**Issue by Jonesie** [mrlacey/BuildTimeHistory#2]
Hi
Im looking for a tool that will centrally record load and build times for solutions so we can optimise our solutions for teams.  I think this could be extended to do this.  What do you think?  From what I can tell:

- HistoryRecord would need to include the solution name (and/or id) and the user name.
- Would be nice to collect machine specs also.
- Data file would include multiple records - 1 for each distinct solution - which creates a compatibility issue.  Perhaps have a diff file name extension.
- Displayed times should include seconds.
- Would be nice to record the load time - is there an OnBeforeSolutionLoad event?
- Data would be uploaded somewhere - maybe just copy the files, ftp or ...  so will require a settings ui I guess.

I can figure out some of these things in a fork but maybe this is something you would like to do ?  Some or all of it :)

**Comment by Jonesie** [comment]
Actually, rather than changing the existing .data files, it could just create a 2nd file with all the details.  Or even just send this data to a service.

**Comment by mrlacey** [comment]
I have other plans for extending this extension and they don't include the above.

It's really easy to add more data to what's recorded but knowing what to record, why, and what to do with it are much more complex. I set out to only record what I knew would be necessary.

> I can figure out some of these things in a fork but maybe this is something you would like to do ? Some or all of it :)

Got a budget for the work?

**Comment by Jonesie** [comment]
Maybe.  Can you provide an estimate so I can ask the PTB?

**Comment by mrlacey** [comment]
> Maybe. Can you provide an estimate so I can ask the PTB?

Please email me directly if still interested in this.
GitHub issues aren't great for discussing potential paid work in public.


Of course, before I could estimate for some work, I'd need to know exactly what you require, not just the vague outline mentioned above.
