### ISSUE TITLE
Change location of displayed info

### ISSUE THREAD

**Issue by Ami-Mizuno** [mrlacey/BuildTimeHistory#3]
It would be nice to allow the info to be placed under the 'Build' category in the output window. By default VS displays that category after each build. Currently you would have to build and then select 'Build time history' from the dropdown.

**Comment by mrlacey** [comment]
But the Build output already includes the time taken for the build -- At least it does for the languages I use.

Do you really need to see the total time taken for all builds after each individual build? Or the number of total builds? What value does that provide?

Also, other people get very upset about adding things to the built-in output panes.
And, there are multiple other extensions that depend on the standardized output of the Build window (pane) to function correctly. I don't want to risk breaking them.

**Comment by Ami-Mizuno** [comment]
Gotcha. It wasn't very important.
