### ISSUE TITLE
Added configuration for displaying total compilation time (seconds/minutes/hours)

### ISSUE THREAD

**Issue by michal-orski** [mrlacey/BuildTimeHistory#4]
For compilations over an hour, the total time is rounded to an hour - so it is not known whether the compilations lasted 68 minutes or 72 minutes - it shows 1 hour.

**Comment by mrlacey** [comment]
When I first created this extension I thought I'd want more precise information about the total build time.
Having used it for several months, I've come to realize that if I spend more than an hour a day waiting for the build, I have bigger issues nd knowing the precise number of minutes isn't all that valuable.

Your projects and workflow may differ, and so I'd be keen to understand what you'd do with this information if available.
How important of an issue is this to you?

**Comment by michal-orski** [comment]
For statistics is very important for me. Of course summary build time higher than 1 hour is the problem itself, but more details can help improvement biggers projects where single build time can take around 5 minuts.

**Comment by mrlacey** [comment]
Can easily add something simple, like this:

![image](https://github.com/mrlacey/BuildTimeHistory/assets/189547/bbc38f36-6f4f-4586-aea8-7bf396e423e6)

**Comment by michal-orski** [comment]
Wow, perfect :)

**Comment by mrlacey** [comment]
v1.2 (with this change) will be in the marketplace shortly.
